# Generated by Django 5.0.7 on 2024-08-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatdata',
            name='extra_images',
        ),
        migrations.RemoveField(
            model_name='boatdata',
            name='image',
        ),
    ]
