# Generated by Django 5.0.7 on 2024-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_boatdata_extra_images_remove_boatdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='boat_id',
            field=models.IntegerField(),
        ),
    ]
